# Generated by Django 6.1 on 2026-09-09 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_booking_live_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandforecast',
            options={'ordering': ['forecast_date', 'category']},
        ),
    ]
