# Generated by Django 6.1 on 2026-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_demandforecast_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('now', 'Book Now'), ('schedule', 'Scheduled')], default='now', max_length=10),
        ),
    ]
